/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbase;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emiko
 */
public class tabela_adresy extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form tabela_klienci
     */
    public tabela_adresy() {
        initComponents();
        setLocationRelativeTo(null);
        Object columns[] = {"ID","ID Pracownika","ID Klienta","ID Autora", "ID Wydawcy", "Miasto","Ulica", "Numer", "Kod pocztowy","Typ","Kraj","Województwo"};
        defaultTableModel.setColumnIdentifiers(columns);
        adresy.setModel(defaultTableModel);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adresy = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        seid = new javax.swing.JTextField();
        scid = new javax.swing.JTextField();
        said = new javax.swing.JTextField();
        spid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        stype = new javax.swing.JTextField();
        scountry = new javax.swing.JTextField();
        sstate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        scity = new javax.swing.JTextField();
        sstreet = new javax.swing.JTextField();
        snumer = new javax.swing.JTextField();
        spostc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adresy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "id_Employee", "id_Customer", "id_Author", "id_Publisher", "City", "Street", "number", "post_code", "type_of_address", "country", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adresy.setColumnSelectionAllowed(true);
        adresy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adresyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adresy);
        adresy.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel1.setText("ID Pracownika");

        jLabel2.setText("ID klienta");

        jLabel3.setText("ID Autora");

        jLabel4.setText("ID Wydawcy");

        seid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seidActionPerformed(evt);
            }
        });

        jButton1.setText("Usuń Zaznaczony");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edytuj Zaznaczony");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Dodaj nowy rekord z danymi z textboxów");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Wróć");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        stype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stypeActionPerformed(evt);
            }
        });

        scountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scountryActionPerformed(evt);
            }
        });

        sstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstateActionPerformed(evt);
            }
        });

        jLabel5.setText("Typ adresu");

        jLabel6.setText("Kraj");

        jLabel7.setText("Województwo");

        jLabel9.setText("Kod pocztowy");

        scity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scityActionPerformed(evt);
            }
        });

        sstreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sstreetActionPerformed(evt);
            }
        });

        snumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snumerActionPerformed(evt);
            }
        });

        jLabel10.setText("Miasto");

        jLabel11.setText("Ulica");

        jLabel12.setText("Numer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(62, 62, 62)
                .addComponent(jButton2)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(sstate, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(snumer, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stype, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scity, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sstreet)
                            .addComponent(spostc)
                            .addComponent(scountry, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seid, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(said, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spid, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scid, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton4)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(seid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(said, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(spid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sstreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(spostc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(snumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(scountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seidActionPerformed

    private void adresyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adresyMouseClicked
        int currentRow = adresy.getSelectedRow();
        //System.out.println(currentRow);
        
        seid.setText(adresy.getValueAt(currentRow,1).toString());
        scid.setText(adresy.getValueAt(currentRow,3).toString());
        said.setText(adresy.getValueAt(currentRow,2).toString());
        spid.setText(adresy.getValueAt(currentRow,4).toString());
        scity.setText(adresy.getValueAt(currentRow,5).toString());
        sstreet.setText(adresy.getValueAt(currentRow,6).toString());
        snumer.setText(adresy.getValueAt(currentRow,7).toString());
        spostc.setText(adresy.getValueAt(currentRow,8).toString());
        stype.setText(adresy.getValueAt(currentRow,9).toString());
        scountry.setText(adresy.getValueAt(currentRow,10).toString());
        sstate.setText(adresy.getValueAt(currentRow,11).toString());
        
    }//GEN-LAST:event_adresyMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //deletacja rekordu
        conn = connect.ConnecrDb();
        if(conn != null){
            String currentID = adresy.getValueAt(adresy.getSelectedRow(),0).toString();
            String sql = "delete from address where id_Adres = '" + currentID + "'";
            try{
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Deletacja zakończona sukcesem");
                defaultTableModel.removeRow(adresy.getSelectedRow());
                clearField();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try {
                    conn.close();
                    pst.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //update rekordu
        conn = connect.ConnecrDb();
         if(conn != null){
            String currentID = adresy.getValueAt(adresy.getSelectedRow(),0).toString();
            String aid = said.getText();
            String cid = scid.getText();
            String eid = seid.getText();
            String pid = spid.getText();
            String type = stype.getText();
            String country = scountry.getText();
            String num = snumer.getText();
            String state = sstate.getText();
            String street = sstreet.getText();
            String post_code = spostc.getText();
            String city = scity.getText();
            
            String sql = "update address set id_Author='" + aid + "', id_Publisher='" + pid + "', id_Employee='" + eid + "', id_Customer='" + cid + "', City='" + city + "', Street='" + street + "', number='" + num + "', post_code='" + post_code + "', type_of_address='" + type + "', country='" + country + "', State='" + state + "' where id_Adres='"+currentID+"'";
             try {
                 pst = conn.prepareStatement(sql);
                 pst.execute();
                 JOptionPane.showMessageDialog(null, "Dane zaktualizowane");
                 defaultTableModel.getDataVector().removeAllElements();
                 defaultTableModel.fireTableDataChanged();
                 loadData();
                 clearField();
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, e);
             }finally{
                try {
                    conn.close();
                    pst.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // dodanie rekordu
        conn = connect.ConnecrDb();
        if(conn != null){
            String sql = "insert into address(id_Employee, id_Customer, id_Author, id_Publisher, City, Street, number, post_code, type_of_address, country, State) values(?,?,?,?,?,?,?,?,?,?,?);";
            try {
                pst = conn.prepareStatement(sql);
                pst.setString(1, seid.getText());
                pst.setString(2, scid.getText());
                pst.setString(3, said.getText());
                pst.setString(4, spid.getText());
                pst.setString(5, scity.getText());
                pst.setString(6, sstreet.getText());
                pst.setString(7, snumer.getText());
                pst.setString(8, spostc.getText());
                pst.setString(9, stype.getText());
                pst.setString(10, scountry.getText());
                pst.setString(11, sstate.getText());

                pst.execute();
                defaultTableModel.getDataVector().removeAllElements();
                defaultTableModel.fireTableDataChanged();
                loadData();
                clearField();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }finally{
                try {
                    conn.close();
                    pst.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        home home = new home();
        home.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void stypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stypeActionPerformed

    private void scountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scountryActionPerformed

    private void scityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scityActionPerformed

    private void snumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snumerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snumerActionPerformed

    private void sstreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sstreetActionPerformed

    private void sstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sstateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabela_adresy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabela_adresy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabela_adresy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabela_adresy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tabela_adresy().setVisible(true);
            }
        });
    }
    
    public void clearField(){
         seid.setText("");
         said.setText("");
         scid.setText("");
         spid.setText("");
         stype.setText("");
         scountry.setText("");
         sstate.setText("");
         sstreet.setText("");
         snumer.setText("");
         spostc.setText("");
         scity.setText("");
    }
    
    public void loadData() {
        conn = connect.ConnecrDb();
        if(conn != null){
            String sql = "select * from address";
            try {
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                
                Object columnData[] = new Object[12];
                while(rs.next()){
                    columnData[0] = rs.getString("id_Adres");
                    columnData[1] = rs.getString("id_Employee");
                    columnData[2] = rs.getString("id_Customer");
                    columnData[3] = rs.getString("id_Author");
                    columnData[4] = rs.getString("id_Publisher");
                    columnData[5] = rs.getString("City");
                    columnData[6] = rs.getString("Street");
                    columnData[7] = rs.getString("number");
                    columnData[8] = rs.getString("post_code");
                    columnData[9] = rs.getString("type_of_address");
                    columnData[10] = rs.getString("country");
                    columnData[11] = rs.getString("State");
                    
                    defaultTableModel.addRow(columnData);
                    
                }
                
                //JOptionPane.showMessageDialog(null, "Display Succeeded");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adresy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField said;
    private javax.swing.JTextField scid;
    private javax.swing.JTextField scity;
    private javax.swing.JTextField scountry;
    private javax.swing.JTextField seid;
    private javax.swing.JTextField snumer;
    private javax.swing.JTextField spid;
    private javax.swing.JTextField spostc;
    private javax.swing.JTextField sstate;
    private javax.swing.JTextField sstreet;
    private javax.swing.JTextField stype;
    // End of variables declaration//GEN-END:variables

    
}
